-- ローカル開発用の初期データ。
--
-- MVP では投入すべきシードデータがない: `words` はユーザーの検索により動的に作られ、
-- `profiles` は auth.users への INSERT トリガーで作成される。
-- 動作確認用のユーザー・データが必要な場合は、実際に signUp フローを通して作成すること
-- (モック禁止方針: docs/adr/0006-no-mocks-testing-policy.md)。
